import { mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";
import type { Manifest } from "../manifest.js";
import type { PlatformAdapter } from "./index.js";
import { buildContextFile, render } from "../render.js";

/**
 * OpenAI Codex CLI adapter.
 *
 * Generates:
 *   - AGENTS.md (repo root)                — auto-loaded project context
 *   - .codex/agents/<name>.md         × 7  — agent prompt bodies (read by orchestrator)
 *   - .codex/orchestrator/<skill>.sh  × 3  — bash chains using `codex exec`
 *   - .codex/FACTORY.md                    — explains the layout and usage
 *
 * The orchestrator scripts implement the chain logic in shell:
 *   - Each agent runs as a separate `codex exec` invocation.
 *   - Outputs are captured and saved under .codex/runs/<timestamp>/.
 *   - Checkpoints pause via `read -p` for human approval.
 *   - Inter-agent context is passed as concatenated text in each prompt.
 *
 * Phase A scope: no automated fix loops; if validator/test-verifier reports
 * failures, the user re-runs or fixes manually. Phase B can add loop logic.
 */
export const codex: PlatformAdapter = {
  name: "codex",
  contextFileName: "AGENTS.md",

  async generate({ targetRoot, manifest, agents, skills, profileBody }) {
    const filesWritten: string[] = [];

    const platformVars = { CONTEXT_FILE: "AGENTS.md" };

    // 1. AGENTS.md at root
    const contextBody = buildContextFile({
      manifest,
      profileBody,
      contextFileName: "AGENTS.md",
      title: `AGENTS.md — ${manifest.name}`,
      platform: "codex",
    });
    const agentsPath = join(targetRoot, "AGENTS.md");
    writeFile(agentsPath, contextBody);
    filesWritten.push(agentsPath);

    // 2. Agent prompt files
    for (const agent of agents) {
      const body = render(agent.body, platformVars);
      const path = join(targetRoot, ".codex", "agents", `${agent.name}.md`);
      writeFile(path, body.trim() + "\n");
      filesWritten.push(path);
    }

    // 3. Bash orchestrator scripts (one per skill)
    const skillNames = new Set(skills.map((s) => s.name));

    if (skillNames.has("feature-factory")) {
      const p = join(targetRoot, ".codex", "orchestrator", "feature-factory.sh");
      writeExecutable(p, featureFactoryScript());
      filesWritten.push(p);
    }
    if (skillNames.has("quick-fix")) {
      const p = join(targetRoot, ".codex", "orchestrator", "quick-fix.sh");
      writeExecutable(p, quickFixScript());
      filesWritten.push(p);
    }
    if (skillNames.has("spike")) {
      const p = join(targetRoot, ".codex", "orchestrator", "spike.sh");
      writeExecutable(p, spikeScript());
      filesWritten.push(p);
    }

    // 4. FACTORY.md
    const factoryPath = join(targetRoot, ".codex", "FACTORY.md");
    writeFile(factoryPath, buildFactoryDoc(manifest, agents.length));
    filesWritten.push(factoryPath);

    return { filesWritten, filesSkipped: [] };
  },
};

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function writeExecutable(path: string, content: string): void {
  writeFile(path, content);
  chmodSync(path, 0o755);
}

/* ------- Bash orchestrator scripts ------- */

function featureFactoryScript(): string {
  return `#!/usr/bin/env bash
# Feature Factory — Tier 3 (full 12-agent chain)
# Generated by ai-factory. Re-run \`factory install\` to regenerate.
set -euo pipefail

if [ \$# -eq 0 ]; then
  echo "Usage: \$0 <feature description>"
  echo ""
  echo "Example: \$0 build invoice reminders for invoices unpaid > 7 days"
  exit 1
fi

REQUEST="\$*"
RUN_DIR=".codex/runs/\$(date +%Y%m%d-%H%M%S)-feature"
mkdir -p "\$RUN_DIR"
echo "\$REQUEST" > "\$RUN_DIR/request.txt"

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CODEX_DIR="\$(dirname "\$SCRIPT_DIR")"

invoke() {
  local agent_name="\$1"
  local prompt_input="\$2"
  local agent_file="\$CODEX_DIR/agents/\$agent_name.md"

  if [ ! -f "\$agent_file" ]; then
    echo "ERROR: agent prompt file not found: \$agent_file" >&2
    exit 1
  fi

  codex exec "\$(cat "\$agent_file")

---

\$prompt_input"
}

section() { echo ""; echo "===== \$1 ====="; echo ""; }

pause_for_approval() {
  echo ""
  read -p "⏸ \$1 (yes / no / edit-then-rerun): " response
  if [ "\$response" != "yes" ] && [ "\$response" != "y" ]; then
    echo "Halted. Outputs in: \$RUN_DIR"
    exit 1
  fi
}

# ----- STEP 1: Researcher -----
section "STEP 1 — Researcher"
RESEARCH=\$(invoke researcher "User request: \$REQUEST")
echo "\$RESEARCH" | tee "\$RUN_DIR/01-researcher.md"

# ----- STEP 2: Story Writer -----
section "STEP 2 — Story Writer"
STORY=\$(invoke story-writer "User request: \$REQUEST

Researcher output:
\$RESEARCH")
echo "\$STORY" | tee "\$RUN_DIR/02-story.md"

pause_for_approval "CHECKPOINT 1: Approve story?"

# ----- STEP 3: Spec Writer -----
section "STEP 3 — Spec Writer"
BRIEF=\$(invoke spec-writer "Approved story:
\$STORY

Researcher output:
\$RESEARCH")
echo "\$BRIEF" | tee "\$RUN_DIR/03-brief.md"

pause_for_approval "CHECKPOINT 2: Approve brief?"

# ----- STEP 4: Migration Author -----
# Returns "Not applicable" if the brief has no schema changes.
section "STEP 4 — Migration Author"
MIGRATION=\$(invoke migration-author "Approved brief:
\$BRIEF

Researcher output:
\$RESEARCH")
echo "\$MIGRATION" | tee "\$RUN_DIR/04-migration.md"

# ----- STEP 5: Backend Builder -----
section "STEP 5 — Backend Builder"
BACKEND=\$(invoke backend-builder "Approved brief:
\$BRIEF

Researcher output:
\$RESEARCH

Migration Author output:
\$MIGRATION")
echo "\$BACKEND" | tee "\$RUN_DIR/05-backend.md"

# ----- STEP 6: Frontend Builder -----
section "STEP 6 — Frontend Builder"
FRONTEND=\$(invoke frontend-builder "Approved brief:
\$BRIEF

Researcher output:
\$RESEARCH

Backend Builder output (includes API contract):
\$BACKEND")
echo "\$FRONTEND" | tee "\$RUN_DIR/06-frontend.md"

# ----- STEP 7: DevOps Builder -----
# Returns "Not applicable" if the brief has no infra/CI changes.
section "STEP 7 — DevOps Builder"
DEVOPS=\$(invoke devops-builder "Approved brief:
\$BRIEF

Researcher output:
\$RESEARCH")
echo "\$DEVOPS" | tee "\$RUN_DIR/07-devops.md"

# ----- STEP 8: Test Verifier -----
section "STEP 8 — Test Verifier"
TEST=\$(invoke test-verifier "Approved story:
\$STORY

Approved brief:
\$BRIEF

Backend Builder summary:
\$BACKEND

Frontend Builder summary:
\$FRONTEND

DevOps Builder summary:
\$DEVOPS")
echo "\$TEST" | tee "\$RUN_DIR/08-test.md"

# ----- STEP 9: Security Reviewer -----
section "STEP 9 — Security Reviewer"
SECURITY=\$(invoke security-reviewer "Approved story:
\$STORY

Approved brief:
\$BRIEF

Backend Builder summary:
\$BACKEND

Frontend Builder summary:
\$FRONTEND

DevOps Builder summary:
\$DEVOPS")
echo "\$SECURITY" | tee "\$RUN_DIR/09-security.md"

# ----- STEP 10: Performance Reviewer -----
section "STEP 10 — Performance Reviewer"
PERF=\$(invoke performance-reviewer "Approved story:
\$STORY

Approved brief:
\$BRIEF

Backend Builder summary:
\$BACKEND

Frontend Builder summary:
\$FRONTEND")
echo "\$PERF" | tee "\$RUN_DIR/10-performance.md"

# ----- STEP 11: Validator -----
section "STEP 11 — Validator"
VALIDATION=\$(invoke validator "Approved story:
\$STORY

Approved brief:
\$BRIEF

Backend Builder summary:
\$BACKEND

Frontend Builder summary:
\$FRONTEND

DevOps Builder summary:
\$DEVOPS")
echo "\$VALIDATION" | tee "\$RUN_DIR/11-validator.md"

# ----- STEP 12: Doc Writer -----
section "STEP 12 — Doc Writer"
DOCS=\$(invoke doc-writer "Approved story:
\$STORY

Approved brief:
\$BRIEF

Backend Builder summary:
\$BACKEND

Frontend Builder summary:
\$FRONTEND

DevOps Builder summary:
\$DEVOPS

Validator findings:
\$VALIDATION

Security Reviewer findings:
\$SECURITY

Performance Reviewer findings:
\$PERF")
echo "\$DOCS" | tee "\$RUN_DIR/12-docs.md"

pause_for_approval "CHECKPOINT 3: Review diff and open PR?"

echo ""
echo "Done. All run outputs saved in: \$RUN_DIR"
`;
}

function quickFixScript(): string {
  return `#!/usr/bin/env bash
# Quick Fix — Tier 2 (single-layer change)
# Generated by ai-factory. Re-run \`factory install\` to regenerate.
set -euo pipefail

if [ \$# -eq 0 ]; then
  echo "Usage: \$0 <description>"
  echo ""
  echo "Example: \$0 fix the invoice PDF missing tenant address"
  exit 1
fi

REQUEST="\$*"
RUN_DIR=".codex/runs/\$(date +%Y%m%d-%H%M%S)-quickfix"
mkdir -p "\$RUN_DIR"

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CODEX_DIR="\$(dirname "\$SCRIPT_DIR")"

invoke() {
  local agent_name="\$1"
  local prompt_input="\$2"
  codex exec "\$(cat "\$CODEX_DIR/agents/\$agent_name.md")

---

\$prompt_input"
}

section() { echo ""; echo "===== \$1 ====="; echo ""; }

# ----- STEP 1: Researcher -----
section "STEP 1 — Researcher"
RESEARCH=\$(invoke researcher "User request: \$REQUEST")
echo "\$RESEARCH" | tee "\$RUN_DIR/01-researcher.md"

# ----- CHECKPOINT: pick builder based on plan -----
echo ""
read -p "⏸ Plan above. Builder to use (backend / frontend): " BUILDER

case "\$BUILDER" in
  backend|be) AGENT=backend-builder ;;
  frontend|fe) AGENT=frontend-builder ;;
  *) echo "Unknown builder: \$BUILDER. Halting."; exit 1 ;;
esac

# ----- STEP 2: Builder -----
section "STEP 2 — \$AGENT"
BUILD=\$(invoke "\$AGENT" "User request: \$REQUEST

Researcher output (treat as mini-spec):
\$RESEARCH")
echo "\$BUILD" | tee "\$RUN_DIR/02-build.md"

# ----- STEP 3: Validator -----
section "STEP 3 — Validator"
VALIDATION=\$(invoke validator "User request (treat as story + brief):
\$REQUEST

Researcher output:
\$RESEARCH

Builder output:
\$BUILD")
echo "\$VALIDATION" | tee "\$RUN_DIR/03-validator.md"

echo ""
echo "Done. All outputs in: \$RUN_DIR"
`;
}

function spikeScript(): string {
  return `#!/usr/bin/env bash
# Spike — Tier 1 (research only)
# Generated by ai-factory. Re-run \`factory install\` to regenerate.
set -euo pipefail

if [ \$# -eq 0 ]; then
  echo "Usage: \$0 <question>"
  echo ""
  echo "Example: \$0 how do we handle Stripe webhook retries?"
  exit 1
fi

REQUEST="\$*"
RUN_DIR=".codex/runs/\$(date +%Y%m%d-%H%M%S)-spike"
mkdir -p "\$RUN_DIR"

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CODEX_DIR="\$(dirname "\$SCRIPT_DIR")"

echo "===== Researcher ====="
echo ""
RESEARCH=\$(codex exec "\$(cat "\$CODEX_DIR/agents/researcher.md")

---

User question: \$REQUEST")
echo "\$RESEARCH" | tee "\$RUN_DIR/researcher.md"

echo ""
echo "Findings above. No code was changed."
echo "To act on this, use:"
echo "  .codex/orchestrator/quick-fix.sh <your build request>"
echo "  .codex/orchestrator/feature-factory.sh <your build request>"
echo ""
echo "Outputs saved in: \$RUN_DIR"
`;
}

/* ------- FACTORY.md ------- */

function buildFactoryDoc(manifest: Manifest, numAgents: number): string {
  return `# AI Factory for Codex CLI

Generated by ai-factory for **${manifest.name}** (layer: ${manifest.layer}, profile: ${manifest.profile}).

Do not hand-edit \`AGENTS.md\`, \`.codex/agents/*\`, or \`.codex/orchestrator/*\` — re-run \`factory install\` after editing \`.factory.yaml\` or the profile.

## What's here

- \`/AGENTS.md\` (repo root) — Codex CLI auto-loads this. Project identity, commands, path scoping, architecture rules, don't-do list.
- \`.codex/agents/<name>.md\` — ${numAgents} agent prompt bodies. Used by the orchestrator scripts.
- \`.codex/orchestrator/<name>.sh\` — executable bash scripts that chain \`codex exec\` calls with checkpoints.
- \`.codex/runs/<timestamp>-<skill>/\` — created at runtime. Holds each step's output (\`01-researcher.md\`, \`02-story.md\`, etc.) for the run.

## Usage

### Tier 3 — full feature

\`\`\`bash
./.codex/orchestrator/feature-factory.sh build invoice reminders for invoices unpaid > 7 days
\`\`\`

The script invokes (12 agents in this order):
1. researcher → story-writer → **⏸ CHECKPOINT 1** (approve story)
2. spec-writer → **⏸ CHECKPOINT 2** (approve brief)
3. migration-author (returns "Not applicable" if no schema changes)
4. backend-builder → frontend-builder → devops-builder (returns "Not applicable" if no infra)
5. test-verifier
6. security-reviewer → performance-reviewer → validator
7. doc-writer → **⏸ CHECKPOINT 3** (review and open PR)

All outputs saved in \`.codex/runs/<timestamp>-feature/\`.

### Tier 2 — small change

\`\`\`bash
./.codex/orchestrator/quick-fix.sh fix the invoice PDF missing tenant address
\`\`\`

researcher → ⏸ (pick backend or frontend) → builder → validator.

### Tier 1 — research only

\`\`\`bash
./.codex/orchestrator/spike.sh how do we handle Stripe webhook retries?
\`\`\`

researcher only. No code written.

## Limitations vs. Claude Code (Phase A)

- **No automated fix loops.** If validator reports Critical findings or test-verifier reports failing ACs, re-run the chain after fixing, or fix manually. Phase B will add automatic fix loops.
- **Path scoping is prompt-only.** Codex doesn't enforce edit paths at the tool level — agents read AGENTS.md and obey.
- **No automatic test/typecheck.** The builders' prompts tell them to run validation commands; the orchestrator script doesn't verify they actually did.
- **Each agent invocation is a fresh \`codex exec\` session.** Context isn't shared — the orchestrator concatenates prior outputs into each prompt explicitly.

## Prerequisites

- \`codex\` CLI installed and authenticated (\`codex login\` if needed).
- Bash 4+ (any modern macOS / Linux).
- Run scripts from the repo root.

## Regenerating

\`\`\`bash
factory install
\`\`\`

Edit \`.factory.yaml\` in the repo root and re-run. Everything in \`AGENTS.md\`, \`.codex/agents/\`, and \`.codex/orchestrator/\` is overwritten. \`.codex/runs/\` is preserved.
`;
}
