import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type { Manifest } from "../manifest.js";
import type { PlatformAdapter } from "./index.js";
import { buildContextFile, render } from "../render.js";

/**
 * Kiro adapter.
 *
 * Generates a `.kiro/steering/` directory:
 *   - `project.md` — always-included context (built from manifest + profile)
 *   - `agent-<name>.md` × 7 — manual-inclusion agent prompts
 *   - `skill-<name>.md` × 3 — manual-inclusion orchestrator skills
 * And a `.kiro/FACTORY.md` companion doc explaining the layout.
 *
 * Invocation in Kiro chat: type `#agent-researcher`, `#skill-feature-factory`, etc.
 * Kiro doesn't have a subagent system, so the chain runs semi-manually — the
 * skill file is the script the user (or Kiro's agentic chat) follows.
 */
export const kiro: PlatformAdapter = {
  name: "kiro",
  contextFileName: ".kiro/steering/project.md",

  async generate({ targetRoot, manifest, agents, skills, profileBody }) {
    const filesWritten: string[] = [];

    const platformVars = {
      CONTEXT_FILE: ".kiro/steering/project.md",
    };

    // 1. Project context — always-included steering file
    const contextBody = buildContextFile({
      manifest,
      profileBody,
      contextFileName: ".kiro/steering/project.md",
      title: `Project context — ${manifest.name}`,
      platform: "kiro",
    });
    const projectFile = wrapSteering("always", contextBody);
    writeFile(join(targetRoot, ".kiro", "steering", "project.md"), projectFile);
    filesWritten.push(join(targetRoot, ".kiro", "steering", "project.md"));

    // 2. Agents — manual-inclusion steering files (invoke via #agent-<name>)
    for (const agent of agents) {
      const body = render(agent.body, platformVars);
      const file = wrapSteering("manual", body);
      const path = join(targetRoot, ".kiro", "steering", `agent-${agent.name}.md`);
      writeFile(path, file);
      filesWritten.push(path);
    }

    // 3. Skills — manual-inclusion steering files (invoke via #skill-<name>)
    for (const skill of skills) {
      const body = render(skill.body, platformVars);
      const file = wrapSteering("manual", body);
      const path = join(targetRoot, ".kiro", "steering", `skill-${skill.name}.md`);
      writeFile(path, file);
      filesWritten.push(path);
    }

    // 4. FACTORY.md — explains the layout
    const factoryDoc = buildFactoryDoc(manifest, agents.length, skills.length);
    const factoryPath = join(targetRoot, ".kiro", "FACTORY.md");
    writeFile(factoryPath, factoryDoc);
    filesWritten.push(factoryPath);

    return { filesWritten, filesSkipped: [] };
  },
};

function wrapSteering(inclusion: "always" | "manual", body: string): string {
  return ["---", `inclusion: ${inclusion}`, "---", "", body.trim(), ""].join("\n");
}

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function buildFactoryDoc(manifest: Manifest, numAgents: number, numSkills: number): string {
  return `# AI Factory in Kiro

Generated by ai-factory for **${manifest.name}** (layer: ${manifest.layer}, profile: ${manifest.profile}).

Do not hand-edit \`.kiro/steering/*\` — re-run \`factory install\` after editing \`.factory.yaml\` or the profile.

## What's here

- \`steering/project.md\` — always-included project context (architecture rules, commands, path scoping, don't-do list). Kiro injects this into every chat session.
- \`steering/agent-*.md\` — ${numAgents} manual-inclusion agent prompts. Invoke by typing \`#agent-<name>\` in Kiro chat.
- \`steering/skill-*.md\` — ${numSkills} manual-inclusion orchestrator scripts. Invoke by typing \`#skill-<name>\`.

## How the chain runs in Kiro

Kiro does not have a Claude-Code-style subagent system, so the chain runs **semi-manually**. The skill file describes the sequence; you (or Kiro's agentic chat) invoke each agent in order, pasting prior output forward.

### Tier 3 — full feature (\`#skill-feature-factory\`)

1. Open Kiro chat. Type:
   \`\`\`
   #skill-feature-factory build invoice reminders for invoices unpaid > 7 days
   \`\`\`
2. Follow the skill's instructions. Each step calls a specific agent in this order:
   \`#agent-researcher\` → \`#agent-story-writer\` → **(approve story)** → \`#agent-spec-writer\` → **(approve brief)** → \`#agent-migration-author\` (skip if no schema changes) → \`#agent-backend-builder\` → \`#agent-frontend-builder\` (skip if backend-only) → \`#agent-devops-builder\` (skip if no infra) → \`#agent-test-verifier\` → \`#agent-security-reviewer\` → \`#agent-performance-reviewer\` → \`#agent-validator\` → \`#agent-doc-writer\`.
3. Review the final diff and open the PR.

### Tier 2 — small change (\`#skill-quick-fix\`)

\`#skill-quick-fix fix the invoice PDF missing the tenant address\` — single builder, faster path.

### Tier 1 — research only (\`#skill-spike\`)

\`#skill-spike how do we handle Stripe webhook retries?\` — read-only investigation.

## Limitations vs. Claude Code

- **No native subagent invocation.** Each agent is a separate \`#\`-mention.
- **No tool scoping.** Path-scoping rules live in the prompts (see \`steering/project.md\`), but Kiro doesn't enforce them at the tool level — agents are trusted to read CLAUDE.md-equivalent (\`project.md\`) and obey.
- **No automatic checkpoint pauses.** The skill text tells the user to stop; you must respect those stops yourself.

## Regenerating

\`\`\`bash
factory install
\`\`\`

Edit \`.factory.yaml\` in the repo root, then re-run. All files in \`.kiro/steering/\` will be overwritten.
`;
}
