import { readFileSync, readdirSync } from "node:fs";
import { resolve, join, basename, extname } from "node:path";
import type { Manifest } from "./manifest.js";

export interface PromptFile {
  name: string;
  body: string;
}

export interface RenderContext {
  manifest: Manifest;
  profileBody: string;
  contextFileName: string;
  /** Optional heading override. If omitted, contextFileName is used. */
  title?: string;
  platform: string;
}

export function loadPrompts(factoryRoot: string): { agents: PromptFile[]; skills: PromptFile[] } {
  return {
    agents: loadDir(join(factoryRoot, "prompts", "agents")),
    skills: loadDir(join(factoryRoot, "prompts", "skills")),
  };
}

export function loadProfile(factoryRoot: string, profileName: string): string {
  const path = resolve(factoryRoot, "profiles", `${profileName}.md`);
  return readFileSync(path, "utf8");
}

function loadDir(dir: string): PromptFile[] {
  return readdirSync(dir)
    .filter((f) => extname(f) === ".md")
    .sort()
    .map((f) => ({
      name: basename(f, ".md"),
      body: readFileSync(join(dir, f), "utf8"),
    }));
}

/**
 * Substitute template variables in a prompt body.
 * Variables are written as {{VAR_NAME}} in the source.
 */
export function render(body: string, vars: Record<string, string>): string {
  return body.replace(/\{\{(\w+)\}\}/g, (match, key: string) => {
    if (key in vars) return vars[key]!;
    return match;
  });
}

/**
 * Build the context-file content from manifest + profile.
 * This is the platform-specific source of truth document (CLAUDE.md, AGENTS.md, etc.).
 */
export function buildContextFile(ctx: RenderContext): string {
  const m = ctx.manifest;
  const lines: string[] = [];

  lines.push(`# ${ctx.title ?? ctx.contextFileName}`);
  lines.push("");
  lines.push(`Generated by ai-factory. Manifest: \`.factory.yaml\`. Profile: \`${m.profile}\`.`);
  lines.push(`Do not hand-edit — edit \`.factory.yaml\` or the profile, then re-run \`factory install\`.`);
  lines.push("");

  lines.push("## Repo identity");
  lines.push("");
  lines.push(`- **Name:** ${m.name}`);
  lines.push(`- **Layer:** ${m.layer}`);
  lines.push(`- **Profile:** ${m.profile}`);
  lines.push("");

  lines.push("## Commands");
  lines.push("");
  lines.push(`- Typecheck: \`${m.commands.typecheck}\``);
  lines.push(`- Lint: \`${m.commands.lint}\``);
  lines.push(`- Test: \`${m.commands.test}\``);
  if (m.commands.acceptance) {
    lines.push(`- Acceptance: \`${m.commands.acceptance}\``);
  }
  lines.push("");

  lines.push("## Path scoping for agents");
  lines.push("");
  if (m.paths.backend && m.paths.backend.length > 0) {
    lines.push("**Backend Builder may edit:**");
    m.paths.backend.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.frontend && m.paths.frontend.length > 0) {
    lines.push("**Frontend Builder may edit:**");
    m.paths.frontend.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.migrations && m.paths.migrations.length > 0) {
    lines.push("**Migration Author may edit:**");
    m.paths.migrations.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.infra && m.paths.infra.length > 0) {
    lines.push("**DevOps Builder may edit:**");
    m.paths.infra.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.tests && m.paths.tests.length > 0) {
    lines.push("**Test Verifier may edit:**");
    m.paths.tests.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.docs && m.paths.docs.length > 0) {
    lines.push("**Doc Writer may edit:**");
    m.paths.docs.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }
  if (m.paths.forbidden && m.paths.forbidden.length > 0) {
    lines.push("**All agents must NOT edit:**");
    m.paths.forbidden.forEach((p) => lines.push(`- \`${p}\``));
    lines.push("");
  }

  lines.push("## Profile rules");
  lines.push("");
  lines.push(ctx.profileBody);
  lines.push("");

  if (m.dontDo && m.dontDo.length > 0) {
    lines.push("## Repo-specific don't-do");
    lines.push("");
    m.dontDo.forEach((rule) => lines.push(`- ${rule}`));
    lines.push("");
  }

  if (m.notes) {
    lines.push("## Notes");
    lines.push("");
    lines.push(m.notes);
    lines.push("");
  }

  return lines.join("\n");
}
